import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Contact Form</h1>

        <p className={styles.description}>
          Interested in Chat? Send me a message
        </p>

        <div className={styles.grid}>
          <form
            data-netlify="true"
            netlify-honeypot="bot-field"
            method="POST"
            name="contact"
            className={styles.form}
          >
            <p hidden>
              <label>
                Don’t fill this out if you’re human: <input name="bot-field" />
              </label>
            </p>
            <input type="hidden" name="form-name" value="contact" />
            <input name="name" type="text" placeholder="Arsalan" />
            <input name="email" type="email" placeholder="me@khattak.dev" />
            <textarea
              name="message"
              placeholder="Your Message comes here"
            ></textarea>
            <input type="submit" value="Send!" />
          </form>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
